"""remove username column

Revision ID: 74dff0ef419c
Revises: 4a3e595ab5d7
Create Date: 2026-07-27 11:35:23.270097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74dff0ef419c'
down_revision: Union[str, Sequence[str], None] = '4a3e595ab5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    # ### end Alembic commands ###
